/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2015-07-04 17:52:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;

public final class viewEmployees_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t\t<title>List of Employees</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t");
 String user = (String)session.getAttribute("user"); 
      out.write("\r\n");
      out.write("\t\t<h5 align=\"right\">Welcome to ");
      out.print( user );
      out.write("</h5>\r\n");
      out.write("\t\t");
 ResultSet rs = (ResultSet)request.getAttribute("resultSet"); 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h4 align=\"center\">List of Employees</h4>\r\n");
      out.write("\t\t<table border=\"1\" align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>E-ID</th>\r\n");
      out.write("\t\t\t\t<th>NAME</th>\r\n");
      out.write("\t\t\t\t<th>PAY</th>\r\n");
      out.write("\t\t\t\t<th>BONUS</th>\r\n");
      out.write("\t\t\t\t<th>UserName</th>\r\n");
      out.write("\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t   <a href=\"AddEmployee.html\">Create</a><br/>\r\n");
      out.write("\t\t            <a href=\"logout.jsp\">login</a><br/>\r\n");
      out.write("\t\t            <a href=\"home.jsp\">Home</a><br/>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");
 while(rs.next()){ 
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( rs.getInt(1) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( rs.getString("ename") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( rs.getDouble(3) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( rs.getDouble(4) );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( rs.getString("uname") );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"edit.jsp?eid=");
      out.print(rs.getInt(1));
      out.write("&ename=");
      out.print(rs.getString(2));
      out.write("&epay=");
      out.print( rs.getDouble(3) );
      out.write("&ebonus=");
      out.print( rs.getDouble(4) );
      out.write("&uname=");
      out.print( rs.getString("uname") );
      out.write("\">Edit</a></td>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"delete?eid=");
      out.print(rs.getInt(1));
      out.write("\">Delete</a></td>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
